title: JSRACS - Student Intranet
description: >- # this means to ignore newlines until "baseurl:"
  A student intranet for John Septimus Roe Anglican Community School
author: github.com/js-jh (Jess Johnson)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://js-jh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
